config/routes.rb
Fulbitofacil::Application.routes.draw do
  resources :user_canchas

  resources :user_locals

  resources :canchas

  resources :locals

  resources :users

end

app/models/local.rb
class Local < ActiveRecord::Base
	has_many :canchas
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locals }
    end
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
    @local = Local.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @local }
    end
  end

  # GET /locals/new
  # GET /locals/new.json
  def new
    @local = Local.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @local }
    end
  end

  # GET /locals/1/edit
  def edit
    @local = Local.find(params[:id])
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(params[:local])

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render json: @local, status: :created, location: @local }
      else
        format.html { render action: "new" }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locals/1
  # PUT /locals/1.json
  def update
    @local = Local.find(params[:id])

    respond_to do |format|
      if @local.update_attributes(params[:local])
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local = Local.find(params[:id])
    @local.destroy

    respond_to do |format|
      format.html { redirect_to locals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/locals/_form.html.erb
<%= form_for(@local) do |f| %>
  <% if @local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @local.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  
    <div class="field">
    <%= f.label :pruebadi %><br />
	<select name="pruebadi"> <option value="">Select Please</option> <option value="1">SURCO</option> <option value="2">MOLINA</option> <option value="3">COMAS</option> </select>
  </div>
  
  <div class="field">
    <%= f.label :addressgmap %><br />
    <%= f.text_field :addressgmap %>
  </div>
  
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing local</h1>

<%= render 'form' %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<h1>Listing locals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Pruebadi</th>
    <th>Addressgmap</th>
    <th>Telefono</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locals.each do |local| %>
  <tr>
    <td><%= local.name %></td>
    <td><%= local.address %></td>
    <td><%= local.pruebadi %></td>
    <td><%= local.addressgmap %></td>
    <td><%= local.telefono %></td>
    <td><%= link_to 'Show', local %></td>
    <td><%= link_to 'Edit', edit_local_path(local) %></td>
    <td><%= link_to 'Destroy', local, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New local</h1>

<%= render 'form' %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @local.name %>
</p>

<p>
  <b>Address:</b>
  <%= @local.address %>
</p>

<p>
  <b>Pruebadi:</b>
  <%= @local.pruebadi %>
</p>

<p>
  <b>Pruebain:</b>
  <%= @local.pruebain %>
</p>

<p>
  <b>Addressgmap:</b>
  <%= @local.addressgmap %>
</p>

<p>
  <b>Telefono:</b>
  <%= @local.telefono %>
</p>


<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>