config/routes.rb
Fulbitofacil::Application.routes.draw do
  resources :user_canchas

  resources :user_locals

  resources :canchas

  resources :locals

  resources :users

end

app/models/cancha.rb
class Cancha < ActiveRecord::Base
	belongs_to : locals
	has_many :user_cancha
	has_many :users, :through => :user_cancha
end

app/controllers/canchas_controller.rb
class CanchasController < ApplicationController
  # GET /canchas
  # GET /canchas.json
  def index
    @canchas = Cancha.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @canchas }
    end
  end

  # GET /canchas/1
  # GET /canchas/1.json
  def show
    @cancha = Cancha.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cancha }
    end
  end

  # GET /canchas/new
  # GET /canchas/new.json
  def new
    @cancha = Cancha.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cancha }
    end
  end

  # GET /canchas/1/edit
  def edit
    @cancha = Cancha.find(params[:id])
  end

  # POST /canchas
  # POST /canchas.json
  def create
    @cancha = Cancha.new(params[:cancha])

    respond_to do |format|
      if @cancha.save
        format.html { redirect_to @cancha, notice: 'Cancha was successfully created.' }
        format.json { render json: @cancha, status: :created, location: @cancha }
      else
        format.html { render action: "new" }
        format.json { render json: @cancha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /canchas/1
  # PUT /canchas/1.json
  def update
    @cancha = Cancha.find(params[:id])

    respond_to do |format|
      if @cancha.update_attributes(params[:cancha])
        format.html { redirect_to @cancha, notice: 'Cancha was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cancha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canchas/1
  # DELETE /canchas/1.json
  def destroy
    @cancha = Cancha.find(params[:id])
    @cancha.destroy

    respond_to do |format|
      format.html { redirect_to canchas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/canchas_helper.rb
module CanchasHelper
end

app/views/canchas/_form.html.erb
<%= simple_form_for(@cancha) do |f| %>
  <%= f.error_notification %>

  <div class="field">
	<%=f.input :namecancha %>
	
  <div class="inputs">
    <%= f.input :pruebaselst %>

  <div class="field">
	<%=f.association :locals %>
	
  </div>	
    
  <div class="field">
	<%=f.input :description %>
	
  </div>
  
    <div class="field">
	<%= f.label :fecha %><br />

    <input id="fecha" name="fecha" type="checkbox" value="Lunes" /> Lunes
	<input id="fecha" name="fecha" type="checkbox" value="Martes" /> Martes
	<input id="fecha" name="fecha" type="checkbox" value="Miercoles" /> Miercoles
	<input id="fecha" name="fecha" type="checkbox" value="Jueves" /> Jueves
	<input id="fecha" name="fecha" type="checkbox" value="Viernes" /> Viernes
	<input id="fecha" name="fecha" type="checkbox" value="Sabado" /> Sabado
	<input id="fecha" name="fecha" type="checkbox" value="Domingo" /> Domingo
	
    </div>
  
  
    <%= f.input :fecpro %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/canchas/edit.html.erb
<h1>Editing cancha</h1>

<%= render 'form' %>

<%= link_to 'Show', @cancha %> |
<%= link_to 'Back', canchas_path %>

app/views/canchas/index.html.erb
<h1>Listing canchas</h1>

<table>
  <tr>
	<th>Namecancha</th>
    <th>Pruebaselst</th>
    <th>Description</th>
	<th>Fecha</th>
	
	
    <th>Fecpro</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @canchas.each do |cancha| %>
  <tr>
	<td><%= cancha.namecancha %></td>
    <td><%= cancha.pruebaselst %></td>
    <td><%= cancha.description %></td>
	<td><%= cancha.fecha %></td>
	
	
    <td><%= cancha.fecpro %></td>
    <td><%= link_to 'Show', cancha %></td>
    <td><%= link_to 'Edit', edit_cancha_path(cancha) %></td>
    <td><%= link_to 'Destroy', cancha, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cancha', new_cancha_path %>

app/views/canchas/new.html.erb
<h1>New cancha</h1>

<%= render 'form' %>

<%= link_to 'Back', canchas_path %>

app/views/canchas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Namecancha:</b>
  <%= @cancha.namecancha %>
</p>

<p>
  <b>Pruebaselst:</b>
  <%= @cancha.pruebaselst %>
</p>

<p>
  <b>Description:</b>
  <%= @cancha.description %>
</p>

<p>
  <b>Fecha:</b>
  <%= @cancha.fecha %>
</p>

<p>
  <b>Fecpro:</b>
  <%= @cancha.fecpro %>
</p>


<%= link_to 'Edit', edit_cancha_path(@cancha) %> |
<%= link_to 'Back', canchas_path %>